---
- name: Install and config wordpress
  hosts: localhost

  tasks:
    - name: Add prometheus repo
      shell: "helm repo add prometheus-community https://prometheus-community.github.io/helm-charts"

    - name: Update repo
      shell: "helm repo update"

    - name: Deploy latest version of prometheus chart inside ingress namespace (and create it)
      shell: "helm upgrade --install prometheus prometheus-community/prometheus -n prometheus --create-namespace"
      # environment:
      #   KUBECONFIG: /root/.kube/config
