version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - cd cicd # change directory
      - chmod +x install-terraform.sh apply-terraform.sh configure-named-profile.sh # make files executable
      - ./install-terraform.sh # install terraform
      - ./configure-named-profile.sh # configure named profile

      - echo Installing tools
      - sudo yum -y install python3-pip
      - sudo pip3 install ansible
      

  build:
    commands:
      - ./apply-terraform.sh
      - aws s3 ls
      #- ansible --version